"""optcon - dimensional, contract-checked physical computation.

The short version of the design: physical quantities carry dimensions *and*
provenance (is this a field amplitude or a power?), and physics invariants are
declared and checked rather than remembered.
"""

from .checks import (
    assert_adjoint,
    assert_gradient_matches,
    assert_passive,
    assert_reciprocal,
    assert_unitary,
    check_gradient,
    dot_test,
    finite_difference_gradient,
    finite_difference_jacobian,
    gain_above_unity,
    is_passive,
    is_reciprocal,
    is_unitary,
    singular_values,
    unitarity_error,
)
from .decision_stability import (
    ChoiceStability,
    DecisionStability,
    ErrorBudget,
    choice_stability,
    threshold_stability,
)
from .errors import (
    AdjointCheckFailure,
    AmplitudeOrderError,
    ContractViolation,
    DimensionError,
    EvidenceGateFailure,
    OptConError,
    UnitError,
)
from .evidence import (
    EvidenceClaim,
    EvidenceDecision,
    EvidenceGateResult,
    EvidenceGraph,
    EvidenceNode,
    EvidenceRecord,
    EvidenceRequirements,
    evaluate_claim,
    evaluate_evidence,
    require_decision_ready,
)
from .fox_li import (
    FoxLiMode,
    FoxLiResonator,
    fox_li_operator,
    fox_li_power_iteration,
    fresnel_number,
    solve_fox_li_modes,
)
from .nlse import (
    FiberParameters,
    NLSEConservationTrace,
    Pulse,
    gaussian_pulse,
    soliton_parameters,
    soliton_pulse,
    solve_nlse,
)
from .quantity import (
    AMPLITUDE,
    POWER,
    RATIO,
    Quantity,
    amplitude_ratio,
    dimensionless,
    power_ratio,
    q,
)
from .quantity import sqrt as sqrt
from .units import Dimension, Unit, unit

__version__ = "0.1.1"

__all__ = [
    "AMPLITUDE",
    "AdjointCheckFailure",
    "AmplitudeOrderError",
    "ChoiceStability",
    "ContractViolation",
    "DecisionStability",
    "Dimension",
    "DimensionError",
    "ErrorBudget",
    "EvidenceClaim",
    "EvidenceDecision",
    "EvidenceGateFailure",
    "EvidenceGateResult",
    "EvidenceGraph",
    "EvidenceNode",
    "EvidenceRecord",
    "EvidenceRequirements",
    "FiberParameters",
    "FoxLiMode",
    "FoxLiResonator",
    "NLSEConservationTrace",
    "OptConError",
    "POWER",
    "Pulse",
    "Quantity",
    "RATIO",
    "Unit",
    "UnitError",
    "amplitude_ratio",
    "assert_adjoint",
    "assert_gradient_matches",
    "assert_passive",
    "assert_reciprocal",
    "assert_unitary",
    "check_gradient",
    "choice_stability",
    "dimensionless",
    "dot_test",
    "evaluate_claim",
    "evaluate_evidence",
    "finite_difference_gradient",
    "finite_difference_jacobian",
    "fox_li_operator",
    "fox_li_power_iteration",
    "fresnel_number",
    "gain_above_unity",
    "gaussian_pulse",
    "is_passive",
    "is_reciprocal",
    "is_unitary",
    "power_ratio",
    "q",
    "require_decision_ready",
    "singular_values",
    "soliton_parameters",
    "soliton_pulse",
    "solve_fox_li_modes",
    "solve_nlse",
    "sqrt",
    "threshold_stability",
    "unit",
    "unitarity_error",
]
